

const names = [
    "Gurubashi Mojo Madness",
    "Alchemists Stone",
    "Flask of Chromatic Resistance",
    "Flask of Distilled Wisdom",
    "Flask of Petrification",
    "Flask of Supreme Power",
    "Flask of the Titans",
    "Major Rejuvenation Potion",
    "Transmute: Elemental Fire",
    "Major Mana Potion",
    "Greater Arcane Protection Potion",
    "Greater Fire Protection Potion",
    "Greater Frost Protection Potion",
    "Greater Nature Protection Potion",
    "Greater Shadow Protection Potion",
    "Major Trolls Blood Potion",
    "Greater Arcane Elixir",
    "Living Action Potion",
    "Purification Potion",
    "Elixir of the Mongoose",
    "Greater Stoneshield Potion",
    "Elixir of Brute Force",
    "Greater Dreamless Sleep Potion",
    "Mageblood Potion",
    "Major Healing Potion",
    "Transmute: Air to Fire",
    "Transmute: Arcanite",
    "Transmute: Earth to Life",
    "Transmute: Earth to Water",
    "Transmute: Fire to Earth",
    "Transmute: Life to Earth",
    "Transmute: Undeath to Water",
    "Transmute: Water to Air",
    "Transmute: Water to Undeath",
    "Elixir of the Sages",
    "Elixir of Superior Defense",
    "Superior Mana Potion",
    "Mighty Rage Potion",
    "Limited Invulnerability Potion",
    "Elixir of Demonslaying",
    "Elixir of Detect Demon",
    "Elixir of Greater Firepower",
    "Elixir of Shadow Power",
    "Stonescale Oil",
    "Elixir of Giants",
    "Ghost Dye",
    "Elixir of Dream Vision",
    "Elixir of Greater Agility",
    "Gift of Arthas",
    "Arcane Elixir",
    "Elixir of Greater Intellect",
    "Invisibility Potion",
    "Dreamless Sleep Potion",
    "Elixir of Detect Undead",
    "Philosophers Stone",
    "Transmute Iron to Gold",
    "Transmute Mithril to Truesilver",
    "Wildvine Potion",
    "Mildly Irradiated Rejuvenation Potion",
    "Elixir of Greater Water Breathing",
    "Lesser Stoneshield Potion",
    "Superior Healing Potion",
    "Restorative Potion",
    "Goblin Rocket Fuel",
    "Magic Resistance Potion",
    "Lesser Arcane Elixir",
    "Greater Mana Potion",
    "Oil of Immolation",
    "Catseye Elixir",
    "Frost Oil",
    "Insulating Gniodine",
    "Elixir of Detect Lesser Invisibility",
    "Elixir of Greater Defense",
    "Elixir of Frost Power",
    "Nature Protection Potion",
    "Frost Protection Potion",
    "Elixir of Agility",
    "Mighty Trolls Blood Potion",
    "Elixir of Fortitude",
    "Great Rage Potion",
    "Fire Protection Potion",
    "Shadow Oil",
    "Lesser Invisibility Potion",
    "Mana Potion",
    "Greater Healing Potion",
    "Elixir of Ogres Strength",
    "Free Action Potion",
    "Elixir of Firepower",
    "Elixir of Lesser Agility",
    "Shadow Protection Potion",
    "Elixir of Defense",
    "Fire Oil",
    "Strong Trolls Blood Potion",
    "Elixir of Poison Resistance",
    "Lesser Mana Potion",
    "Healing Potion",
    "Minor Magic Resistance Potion",
    "Holy Protection Potion",
    "Swim Speed Potion",
    "Elixir of Giant Growth",
    "Elixir of Water Breathing",
    "Elixir of Wisdom",
    "Elixir of Coalesced Regret",
    "Blackmouth Oil",
    "Rage Potion",
    "Swiftness Potion",
    "Lesser Healing Potion",
    "Discolored Healing Potion",
    "Elixir of Minor Agility",
    "Elixir of Minor Fortitude",
    "Minor Rejuvenation Potion",
    "Minor Mana Potion",
    "Weak Trolls Blood Potion",
    "Elixir of Lions Strength",
    "Elixir of Minor Defense",
    "Minor Healing Potion",
    "Cowardly Flight Potion",
    "Elixir of Tongues",
    "Elixir of Waterwalking",
    "Greater Holy Protection Potion",
    "Refined Scale of Onyxia"
]

//Porotyping removal of string white spaces
// const potion = "Elixir of Tongues"
// console.log(potion.replace(/\s/g, ""));

//let stringNames = names.toString(); //converts the names array into a string called stringNames
// console.log(stringNames);
//console.log(stringNames.replace(/\s/g, "")); //replaces all white strings in stringNames with a no-white space version of itself to be put into the potionNames object


const potionNames = {
// GurubashiMojoMadness,
// AlchemistsStone,
// FlaskofChromaticResistance,
// FlaskofDistilledWisdom,
// FlaskofPetrification,
// FlaskofSupremePower,
// FlaskoftheTitans,
// MajorRejuvenationPotion,
// TransmuteElementalFire,
// MajorManaPotion,
// GreaterArcaneProtectionPotion,
// GreaterFireProtectionPotion,
// GreaterFrostProtectionPotion,
// GreaterNatureProtectionPotion,
// GreaterShadowProtectionPotion,
// MajorTrollsBloodPotion,
// GreaterArcaneElixir,
// LivingActionPotion,
// PurificationPotion,
// ElixiroftheMongoose,
// GreaterStoneshieldPotion,
// ElixirofBruteForce,
// GreaterDreamlessSleepPotion,
// MagebloodPotion,
// MajorHealingPotion,
// TransmuteAirtoFire,
// TransmuteArcanite,
// TransmuteEarthtoLife,
// TransmuteEarthtoWater,
// TransmuteFiretoEarth,
// TransmuteLifetoEarth,
// TransmuteUndeathtoWater,
// TransmuteWatertoAir,
// TransmuteWatertoUndeath,
// ElixiroftheSages,
// ElixirofSuperiorDefense,
// SuperiorManaPotion,
// MightyRagePotion,
// LimitedInvulnerabilityPotion,
// ElixirofDemonslaying,
// ElixirofDetectDemon,
// ElixirofGreaterFirepower,
// ElixirofShadowPower,
// StonescaleOil,
// ElixirofGiants,
// GhostDye,
// ElixirofDreamVision,
// ElixirofGreaterAgility,
// GiftofArthas,
// ArcaneElixir,
// ElixirofGreaterIntellect,
// InvisibilityPotion,
// DreamlessSleepPotion,
// ElixirofDetectUndead,
// PhilosophersStone,
// TransmuteIrontoGold,
// TransmuteMithriltoTruesilver,
// WildvinePotion,
// MildlyIrradiatedRejuvenationPotion,
// ElixirofGreaterWaterBreathing,
// LesserStoneshieldPotion,
// SuperiorHealingPotion,
// RestorativePotion,
// GoblinRocketFuel,
// MagicResistancePotion,
// LesserArcaneElixir,
// GreaterManaPotion,
// OilofImmolation,
// CatseyeElixir,
// FrostOil,
// InsulatingGniodine,
// ElixirofDetectLesserInvisibility,
// ElixirofGreaterDefense,
// ElixirofFrostPower,
// NatureProtectionPotion,
// FrostProtectionPotion,
// ElixirofAgility,
// MightyTrollsBloodPotion,
// ElixirofFortitude,
// GreatRagePotion,
// FireProtectionPotion,
// ShadowOil,
// LesserInvisibilityPotion,
// ManaPotion,
// GreaterHealingPotion,
// ElixirofOgresStrength,
FreeActionPotion: ["blackmouth oilx2", "stranglekelp", "leaded vial"],
// ElixirofFirepower,
// ElixirofLesserAgility,
ShadowProtectionPotion: ["grave moss", "kingsblood", "leaded vial"],
ElixirofDefense: ["wild steelbloom", "stranglekelp", "leaded vial"],
// FireOil,
// StrongTrollsBloodPotion,
// ElixirofPoisonResistance,
// LesserManaPotion,
// HealingPotion,
// MinorMagicResistancePotion,
// HolyProtectionPotion,
// SwimSpeedPotion,
// ElixirofGiantGrowth,
// ElixirofWaterBreathing,
// ElixirofWisdom,
// ElixirofCoalescedRegret,
// BlackmouthOil,
// RagePotion,
// SwiftnessPotion,
// LesserHealingPotion,
// DiscoloredHealingPotion,
// ElixirofMinorAgility,
// ElixirofMinorFortitude,
// MinorRejuvenationPotion,
// MinorManaPotion,
// WeakTrollsBloodPotion,
// ElixirofLionsStrength,
// ElixirofMinorDefense,
// MinorHealingPotion,
// CowardlyFlightPotion,
// ElixirofTongues,
// ElixirofWaterwalking,
// GreaterHolyProtectionPotion,
// RefinedScaleofOnyxia

}

console.log(Object.values(potionNames.FreeActionPotion));

 //key is a variable that is defined to use in the for loop  //this searches for keys... How do i search just the values, ie: every instance of said value "stranglekelp"


function ingredientSearch(ingredient) {
for (const [key, value] of Object.entries(potionNames)) {  // Querie: for of loop to determine whether or not "stranglekelp" is included in the value field of object: potionNames
    if (value.includes(ingredient)) {
    console.log(`Key: ${key}, Value: ${value}`)
    } 
}
}

ingredientSearch("stranglekelp");